### ISSUE TITLE
The transactionTimeout format has to be number.

### ISSUE THREAD

**Issue by johna1203** [alexa/amazon-pay-alexa-utils-for-nodejs#3]
I had problems passing the transactionTimeout as a string, so I think the transactionTimeout should be passed as a number. 
I wrote the detail in the link below.

https://github.com/alexa/amazon-pay-alexa-utils-for-nodejs/commit/b42f5a40a3bb3ea585982dd53aa9d933cd29124f

**Comment by danielneu** [comment]
Thanks Jonathan!

I updated the ```transactionTimeout``` to be a number now.
In addition to your suggested changes, I also updated a couple of builders and tests.

Please use version 1.3.4, which has all the updates.

Resolving.
